theme: jekyll-theme-hacker
show_downloads: true
title: Gamersclub Booster
description: Extensão para navegadores com o intuito de melhorar a plataforma Gamersclub
chrome_store_url: https://chrome.google.com/webstore/detail/gamersclub-booster/dahnmmlhchpmmlgebpkpaofbefjdlpin
firefox_store_url: https://addons.mozilla.org/pt-BR/firefox/addon/gamersclub-booster/
